![istockphoto-1317661209-170667a](https://user-images.githubusercontent.com/98513548/153158691-ccaad887-26a2-4b23-9000-86754d36d629.jpg)

# KarlGeorgeAstudillo
IT student

Personal profile: I'm a student in Univeristy of Baguio who are currently taking BSIT and I'm 20 years old

Address: Purok 1 Pinsao proper

Education: 
           Grade School 2009 - 2014 @ SCS

           High School  2014 - 2020 @ SMS
           
           College      2020 - Present @ University of Baguio
          
Phone number: 09398779211

Email: karlgeorgeastudillo@gmail.com
